name: neural_priors
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - tensorflow=2.14
  - tensorflow-probability
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - scipy
  - scikit-learn
  - jupyter
  - pip
  - pip:
      - tensorflow-addons
      - tqdm
      - nilearn
